# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  
  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    supportedFilesystems = [ "ntfs" ];
  };
  #boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/76688632-d388-436b-b92f-19d59fd64535";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8AD0-8095";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # HDD1
   fileSystems."/home/lexi/HDD1" =
    { device = "/dev/disk/by-uuid/8CD8D180D8D1694A";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

  fileSystems."/home/lexi/HDD2" =
    { device = "/dev/disk/by-uuid/52FA7085FA7066DF";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };
  # HDD2
  #fileSystems."/home/lexi/HDD2" =
  #  { device = "/dev/sdb5";
  #    fsType = "ntfs-3g"; 
  #    options = [ "rw" "uid=1000"];
  #  };

  # Volume:      8CD8D180D8D1694A
  # New Volume:  52FA7085FA7066DF

  swapDevices =
    [ { device = "/dev/disk/by-uuid/84771ef9-93d6-4ab4-b6f9-6f1556795250"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
