{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    # AdoptOpenJDK
    ali
    angryipscanner
    ani-cli
    arandr
    fastfetch
    fuzzel
    git
    greetd.tuigreet
    libnotify
    lshw
    lutris-free
    magic-wormhole-rs
    micro
    neofetch
    networkmanagerapplet
    nil
    nixd
    nixfmt-rfc-style
    ntfs3g
    mangohud
    parsec-bin
    parted
    pavucontrol
    polkit
    pulseaudio
    simple-scan
    sshfs
    swaybg
    system-config-printer
    typst
    subfinder
    temurin-bin
    udiskie
    udisks
    usbutils
    wget
    wineWowPackages.waylandFull
    wireshark
    wireguard-tools
    xwayland-satellite
  ];
}
